### ISSUE TITLE
Changes required for mongoid4

### ISSUE THREAD

**Issue by rbclark** [pophealth/quality-measure-engine#19]
Since rails 4 has been released and mongoid 4 is about to be released, an experimental branch for this repository running mongoid 4 would be helpful for keeping the development in one place. I currently have a version of QME that has all tests passing and running on mongoid4, however I cannot put in a pull request until there is a branch to push it to.

**Comment by eedrummer** [comment]
Done: https://github.com/pophealth/quality-measure-engine/tree/experimental_mongoid4
